import type { Metadata } from "next";
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/navbar";
import Link from "next/link";
import CircularText from "@/components/CircularText";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative bg-[#FFFCF5]">
        <Navbar />
        {children}
        <div className="fixed bottom-6 right-6 z-50 pointer-events-none">
          <Link
            href="/ContactUs"
            className="pointer-events-auto relative block group cursor-pointer"
            aria-label="Contact Us"
          >
            <CircularText
              text="CAN WE CONNECT TODAY? • "
              spinDuration={8}
              onHover="speedUp"
              className="w-24 h-24 text-[8px] uppercase font-bold text-white tracking-wider bg-[#25d366] backdrop-blur-md rounded-full shadow-lg border border-[#25d366]/40 flex items-center justify-center transition-all duration-300 hover:scale-105 hover:bg-[#25d366] hover:border-[#25d366]/50 hover:shadow-xl"
              radius={38}
            />
            {/* Center Dot */}
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              <div className="w-2 h-2 bg-white rounded-full animate-pulse group-hover:scale-125 transition-transform duration-300" />
            </div>
          </Link>
        </div>
      </body>
    </html>
  );
}


